-- V1: initial Arktos schema.
--
-- Ownership: api_keys 1─* wallets 1─* accounts.
-- Secrets: only wallets.encrypted_passphrase (AES-256-GCM envelope, see
-- src/crypto.rs). Accounts hold public data only; private keys are re-derived
-- from the recovery phrase and never stored.
-- Timestamps: UTC, ISO-8601 with milliseconds, generated by SQLite.

CREATE TABLE api_keys (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    -- HMAC-SHA256 (hex) of the client API key; the key itself is never stored.
    key_hash    TEXT    NOT NULL UNIQUE CHECK (length(key_hash) = 64),
    key_name    TEXT    NOT NULL CHECK (length(key_name) BETWEEN 1 AND 255),
    is_revoked  INTEGER NOT NULL DEFAULT 0 CHECK (is_revoked IN (0, 1)),
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE TABLE wallets (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    key_id                INTEGER NOT NULL REFERENCES api_keys (id) ON DELETE RESTRICT,
    name                  TEXT    NOT NULL CHECK (length(name) BETWEEN 1 AND 255),
    encrypted_passphrase  TEXT    NOT NULL,
    created_at            TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    -- One wallet name per API-key owner.
    UNIQUE (key_id, name)
) STRICT;

CREATE TABLE accounts (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    wallet_id        INTEGER NOT NULL REFERENCES wallets (id) ON DELETE RESTRICT,
    chain_type       TEXT    NOT NULL CHECK (chain_type IN ('Bitcoin', 'Ethereum')),
    -- Non-hardened BIP32 child index.
    account_index    INTEGER NOT NULL CHECK (account_index BETWEEN 0 AND 2147483647),
    derivation_path  TEXT    NOT NULL,
    public_key       TEXT    NOT NULL,
    address          TEXT    NOT NULL,
    created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    -- One account per wallet, chain and index.
    UNIQUE (wallet_id, chain_type, account_index),
    -- The stored path must be the canonical path for chain + index
    -- (see wallet_manager::derivation_path).
    CHECK (
        (chain_type = 'Bitcoin'  AND derivation_path = 'm/86''/0''/0''/0/'  || account_index) OR
        (chain_type = 'Ethereum' AND derivation_path = 'm/44''/60''/0''/0/' || account_index)
    )
) STRICT;
