//! Persistence records. These are internal: they are never serialized to
//! clients (API responses live in `wallet_services`), and their `Debug`
//! output redacts encrypted fields.

use crate::domain::Network;
use std::fmt;

/// A row of `wallets`.
#[derive(Clone, PartialEq)]
pub struct Wallet {
    pub id: i64,
    pub name: String,
    /// Encrypted recovery phrase (v1 envelope, see `crypto`).
    pub encrypted_passphrase: String,
    /// RFC 3339 UTC timestamp generated by SQLite.
    pub created_at: String,
}

impl fmt::Debug for Wallet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Wallet")
            .field("id", &self.id)
            .field("name", &self.name)
            .field("encrypted_passphrase", &"[REDACTED]")
            .field("created_at", &self.created_at)
            .finish()
    }
}

/// A row of `accounts` (public data only).
#[derive(Debug, Clone, PartialEq)]
pub struct Account {
    pub id: i64,
    pub wallet_id: i64,
    pub network: Network,
    /// Non-hardened BIP32 address index (last path component).
    pub account_index: u32,
    /// Canonical path (see `Network::derivation_path`).
    pub derivation_path: String,
    /// Bitcoin: bech32m; Ethereum: canonical lowercase hex (EIP-55 is applied
    /// when returned to clients).
    pub address: String,
    /// Compressed SEC1 public key, `0x`-hex.
    pub public_key: String,
    /// RFC 3339 UTC timestamp generated by SQLite.
    pub created_at: String,
}
